# Generated by Django 5.2.13 on 2026-06-17 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('matricule', models.CharField(blank=True, max_length=50)),
                ('fonction', models.CharField(choices=[('terrain', 'terrain'), ('encadrement', 'encadrement'), ('commandement', 'commandement')], default='encadrement', max_length=32)),
                ('grade', models.CharField(blank=True, max_length=120)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profil utilisateur',
                'verbose_name_plural': 'profils utilisateurs',
            },
        ),
    ]
