# Generated by Django 5.2.13 on 2026-09-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_must_change_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('identifier', models.CharField(db_index=True, max_length=255)),
                ('ip', models.CharField(blank=True, default='', max_length=64)),
                ('success', models.BooleanField(default=False)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['identifier', 'created_at'], name='accounts_lo_identif_19f84b_idx')],
            },
        ),
    ]
