# Generated by Django 5.2.13 on 2026-09-14 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_login_attempt'),
        ('etudiants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_email', models.CharField(blank=True, default='', max_length=255)),
                ('actor_role', models.CharField(blank=True, default='', max_length=64)),
                ('ip', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('action', models.CharField(choices=[('VIEW', 'Consultation'), ('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('DOWNLOAD', 'Téléchargement'), ('IMPORT', 'Import'), ('LOGIN_SUCCESS', 'Connexion réussie'), ('LOGIN_FAIL', 'Connexion échouée'), ('LOGOUT', 'Déconnexion'), ('PASSWORD_CHANGE', 'Changement mot de passe'), ('PASSWORD_RESET', 'Réinitialisation mot de passe')], db_index=True, max_length=32)),
                ('resource_type', models.CharField(db_index=True, max_length=64)),
                ('resource_id', models.CharField(blank=True, default='', max_length=64)),
                ('eleve_matricule', models.CharField(blank=True, default='', max_length=64)),
                ('path', models.CharField(blank=True, default='', max_length=512)),
                ('method', models.CharField(blank=True, default='', max_length=16)),
                ('summary', models.CharField(blank=True, default='', max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('success', models.BooleanField(default=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('eleve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='etudiants.eleve')),
            ],
            options={
                'verbose_name': 'événement d’audit',
                'verbose_name_plural': 'événements d’audit',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['eleve', 'created_at'], name='accounts_au_eleve_i_c7cf6e_idx'), models.Index(fields=['actor', 'created_at'], name='accounts_au_actor_i_e03d4d_idx'), models.Index(fields=['action', 'created_at'], name='accounts_au_action_6cf40e_idx'), models.Index(fields=['resource_type', 'resource_id'], name='accounts_au_resourc_9749c3_idx')],
            },
        ),
    ]
