# Generated by Django 5.2.13 on 2026-09-14 19:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_audit_event'),
        ('etudiants', '0003_phase12_13_version_and_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('eleve__isnull', False), ('fonction', 'etudiant')), fields=('eleve',), name='uniq_student_profile_per_eleve'),
        ),
    ]
