# Generated by Django 5.2.13 on 2026-09-14 19:04

import django.db.models.deletion
import etudiants.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etudiants', '0002_phase9_operations_scolarite'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppelPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField()),
                ('statut', models.CharField(default='transmis', max_length=40)),
                ('section', models.CharField(blank=True, default='', max_length=100)),
                ('type', models.CharField(choices=[('matin', 'Matin'), ('apres_midi', 'Après-midi'), ('exceptionnel', 'Exceptionnel')], default='matin', max_length=20)),
                ('compagnie', models.CharField(blank=True, default='', max_length=100)),
                ('superviseur', models.CharField(blank=True, default='', max_length=150)),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['compagnie', 'section', 'date'], name='operations__compagn_29d6f2_idx')],
            },
        ),
        migrations.CreateModel(
            name='DroitsBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annee', models.PositiveIntegerField()),
                ('mois', models.PositiveSmallIntegerField()),
                ('compagnie', models.CharField(max_length=100)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('default_montant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'ordering': ['-annee', '-mois', 'compagnie'],
                'unique_together': {('annee', 'mois', 'compagnie')},
            },
        ),
        migrations.CreateModel(
            name='AppelLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent')], default='present', max_length=20)),
                ('motif', models.CharField(blank=True, choices=[('medical', 'Médical'), ('social', 'Social'), ('familial', 'Familial'), ('administratif', 'Administratif'), ('permission', 'Permission'), ('mission', 'Mission'), ('non_justifie', 'Non justifié')], max_length=32, null=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presence_lignes', to='etudiants.eleve')),
                ('appel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='operations.appelpresence')),
            ],
            options={
                'unique_together': {('appel', 'eleve')},
            },
        ),
        migrations.CreateModel(
            name='ConsultationMedicale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, default='', max_length=64)),
                ('type', models.CharField(choices=[('consultation', 'Consultation'), ('incident', 'Incident médical')], default='consultation', max_length=20)),
                ('motif', models.TextField(blank=True, default='')),
                ('date_consultation', models.DateField(blank=True, null=True)),
                ('avis_infirmerie', models.TextField(blank=True, default='')),
                ('pj_pdf', models.FileField(blank=True, null=True, upload_to='operations/medical/%Y/%m/', validators=[etudiants.validators.validate_document_file])),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations_medicales', to='etudiants.eleve')),
            ],
            options={
                'ordering': ['-date_consultation', '-id'],
                'indexes': [models.Index(fields=['eleve', 'type'], name='operations__eleve_i_f9d86c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, default='', max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('nature', models.CharField(choices=[('permission_sortie', 'Permission de sortie'), ('autorisation_sortie', 'Autorisation de sortie'), ('demande_document', 'Demande de document'), ('demande_stage', 'Demande de stage'), ('divers', 'Divers')], default='divers', max_length=40)),
                ('date_depot', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('annulee', 'Annulée')], default='en_cours', max_length=20)),
                ('demande_pdf', models.FileField(blank=True, null=True, upload_to='operations/demandes/%Y/%m/', validators=[etudiants.validators.validate_document_file])),
                ('pj_pdf', models.FileField(blank=True, null=True, upload_to='operations/demandes_pj/%Y/%m/', validators=[etudiants.validators.validate_document_file])),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='etudiants.eleve')),
            ],
            options={
                'ordering': ['-date_depot', '-id'],
                'indexes': [models.Index(fields=['eleve', 'statut'], name='operations__eleve_i_49d84e_idx')],
            },
        ),
        migrations.CreateModel(
            name='DroitsLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('etat', models.CharField(choices=[('percu', 'Perçu'), ('non_percu', 'Non perçu')], default='non_percu', max_length=20)),
                ('remarques', models.TextField(blank=True, default='')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='operations.droitsbatch')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='droits_lignes', to='etudiants.eleve')),
            ],
            options={
                'ordering': ['eleve_id'],
                'unique_together': {('batch', 'eleve')},
            },
        ),
        migrations.CreateModel(
            name='EquipementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, default='', max_length=64)),
                ('nature', models.CharField(blank=True, default='', max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('date_remise', models.DateField(blank=True, null=True)),
                ('etat', models.CharField(choices=[('en_usage', 'Utilisé'), ('rendu', 'Rendu')], default='en_usage', max_length=20)),
                ('date_retour', models.DateField(blank=True, null=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='operations/equipement/%Y/%m/', validators=[etudiants.validators.validate_document_file])),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipement_items', to='etudiants.eleve')),
            ],
            options={
                'ordering': ['-date_remise', '-id'],
                'indexes': [models.Index(fields=['eleve', 'etat'], name='operations__eleve_i_8a3423_idx')],
            },
        ),
        migrations.CreateModel(
            name='JournalEvenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, default='', max_length=64)),
                ('type', models.CharField(choices=[('observation', 'Observation'), ('felicitation', 'Félicitation'), ('incident', 'Incident'), ('consigne', 'Consigne'), ('encadrement', 'Encadrement'), ('divers', 'Divers')], default='observation', max_length=32)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('titre', models.CharField(blank=True, default='', max_length=200)),
                ('contenu', models.TextField(blank=True, default='')),
                ('auteur', models.CharField(blank=True, default='', max_length=150)),
                ('source', models.CharField(choices=[('manuel', 'Manuel'), ('systeme', 'Système')], default='manuel', max_length=20)),
                ('pj_pdf', models.FileField(blank=True, null=True, upload_to='operations/journal/%Y/%m/', validators=[etudiants.validators.validate_document_file])),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_evenements', to='etudiants.eleve')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['eleve', 'type'], name='operations__eleve_i_f13711_idx')],
            },
        ),
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, default='', max_length=64)),
                ('motif', models.TextField(blank=True, default='')),
                ('nature', models.CharField(choices=[('avertissement', 'Avertissement'), ('blame', 'Blâme'), ('retrait', 'Retrait'), ('consigne', 'Consigne'), ('heures_sup', 'Heures supplémentaires'), ('autre', 'Autre')], default='avertissement', max_length=32)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('cloturee', 'Clôturée'), ('annulee', 'Annulée')], default='en_cours', max_length=20)),
                ('cr_pdf', models.FileField(blank=True, null=True, upload_to='operations/sanctions_cr/%Y/%m/', validators=[etudiants.validators.validate_document_file])),
                ('pj_pdf', models.FileField(blank=True, null=True, upload_to='operations/sanctions_pj/%Y/%m/', validators=[etudiants.validators.validate_document_file])),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to='etudiants.eleve')),
            ],
            options={
                'ordering': ['-date_debut', '-id'],
                'indexes': [models.Index(fields=['eleve', 'statut'], name='operations__eleve_i_f0c966_idx')],
            },
        ),
    ]
