# Generated by Django 5.2.13 on 2026-09-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_phase9_operations_scolarite'),
    ]

    operations = [
        migrations.AddField(
            model_name='appelligne',
            name='row_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='appelpresence',
            name='row_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='consultationmedicale',
            name='row_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='demande',
            name='row_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='droitsbatch',
            name='row_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='droitsligne',
            name='row_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='equipementitem',
            name='row_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='journalevenement',
            name='row_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sanction',
            name='row_version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
