"""Geo reference data for dossier Excel template (mirrors front pays + wilayas)."""
from __future__ import annotations

PAYS_LIST: list[str] = [
    'Mauritanie',
    'Afghanistan',
    'Afrique du Sud',
    'Albanie',
    'Algérie',
    'Allemagne',
    'Andorre',
    'Angola',
    'Antigua-et-Barbuda',
    'Arabie saoudite',
    'Argentine',
    'Arménie',
    'Australie',
    'Autriche',
    'Azerbaïdjan',
    'Bahamas',
    'Bahreïn',
    'Bangladesh',
    'Barbade',
    'Belgique',
    'Belize',
    'Bénin',
    'Bhoutan',
    'Biélorussie',
    'Birmanie',
    'Bolivie',
    'Bosnie-Herzégovine',
    'Botswana',
    'Brésil',
    'Brunei',
    'Bulgarie',
    'Burkina Faso',
    'Burundi',
    'Cambodge',
    'Cameroun',
    'Canada',
    'Cap-Vert',
    'Chili',
    'Chine',
    'Chypre',
    'Colombie',
    'Comores',
    'Congo',
    'Corée du Nord',
    'Corée du Sud',
    'Costa Rica',
    'Côte d’Ivoire',
    'Croatie',
    'Cuba',
    'Danemark',
    'Djibouti',
    'Dominique',
    'Égypte',
    'Émirats arabes unis',
    'Équateur',
    'Érythrée',
    'Espagne',
    'Estonie',
    'Eswatini',
    'États-Unis',
    'Éthiopie',
    'Fidji',
    'Finlande',
    'France',
    'Gabon',
    'Gambie',
    'Géorgie',
    'Ghana',
    'Grèce',
    'Grenade',
    'Guatemala',
    'Guinée',
    'Guinée-Bissau',
    'Guinée équatoriale',
    'Guyana',
    'Haïti',
    'Honduras',
    'Hongrie',
    'Inde',
    'Indonésie',
    'Irak',
    'Iran',
    'Irlande',
    'Islande',
    'Israël',
    'Italie',
    'Jamaïque',
    'Japon',
    'Jordanie',
    'Kazakhstan',
    'Kenya',
    'Kirghizistan',
    'Kiribati',
    'Kosovo',
    'Koweït',
    'Laos',
    'Lesotho',
    'Lettonie',
    'Liban',
    'Libéria',
    'Libye',
    'Liechtenstein',
    'Lituanie',
    'Luxembourg',
    'Macédoine du Nord',
    'Madagascar',
    'Malaisie',
    'Malawi',
    'Maldives',
    'Mali',
    'Malte',
    'Maroc',
    'Maurice',
    'Mexique',
    'Micronésie',
    'Moldavie',
    'Monaco',
    'Mongolie',
    'Monténégro',
    'Mozambique',
    'Namibie',
    'Nauru',
    'Népal',
    'Nicaragua',
    'Niger',
    'Nigéria',
    'Norvège',
    'Nouvelle-Zélande',
    'Oman',
    'Ouganda',
    'Ouzbékistan',
    'Pakistan',
    'Palaos',
    'Palestine',
    'Panama',
    'Papouasie-Nouvelle-Guinée',
    'Paraguay',
    'Pays-Bas',
    'Pérou',
    'Philippines',
    'Pologne',
    'Portugal',
    'Qatar',
    'République centrafricaine',
    'République démocratique du Congo',
    'République dominicaine',
    'République tchèque',
    'Roumanie',
    'Royaume-Uni',
    'Russie',
    'Rwanda',
    'Saint-Christophe-et-Niévès',
    'Sainte-Lucie',
    'Saint-Marin',
    'Saint-Vincent-et-les-Grenadines',
    'Salomon',
    'Salvador',
    'Samoa',
    'Sao Tomé-et-Principe',
    'Sénégal',
    'Serbie',
    'Seychelles',
    'Sierra Leone',
    'Singapour',
    'Slovaquie',
    'Slovénie',
    'Somalie',
    'Soudan',
    'Soudan du Sud',
    'Sri Lanka',
    'Suède',
    'Suisse',
    'Suriname',
    'Syrie',
    'Tadjikistan',
    'Tanzanie',
    'Tchad',
    'Thaïlande',
    'Timor oriental',
    'Togo',
    'Tonga',
    'Trinité-et-Tobago',
    'Tunisie',
    'Turkménistan',
    'Turquie',
    'Tuvalu',
    'Ukraine',
    'Uruguay',
    'Vanuatu',
    'Vatican',
    'Venezuela',
    'Viêt Nam',
    'Yémen',
    'Zambie',
    'Zimbabwe',
]

WILAYAS_MR: list[dict[str, object]] = [
    {
        'nom': 'Nouakchott-Nord',
        'communes': ['Dar Naïm', 'Teyarett', 'Toujounine'],
    },
    {
        'nom': 'Nouakchott-Ouest',
        'communes': ['Tevragh-Zeïna', 'Ksar', 'Sebkha'],
    },
    {
        'nom': 'Nouakchott-Sud',
        'communes': ['Arafat', 'El Mina', 'Riyad'],
    },
    {
        'nom': 'Adrar',
        'communes': ['Atar', 'Aoujeft', 'Chinguetti', 'Ouadane'],
    },
    {
        'nom': 'Assaba',
        'communes': ['Kiffa', 'Barkéol', 'Boumdeid', 'Guérou', 'Kankossa'],
    },
    {
        'nom': 'Brakna',
        'communes': ['Aleg', 'Bababé', 'Boghé', 'M’Bagne', 'Magta-Lahjar'],
    },
    {
        'nom': 'Dakhlet Nouadhibou',
        'communes': ['Nouadhibou', 'Boulenouar'],
    },
    {
        'nom': 'Gorgol',
        'communes': ['Kaédi', 'Maghama', 'Monguel', 'M’Bout'],
    },
    {
        'nom': 'Guidimakha',
        'communes': ['Sélibaby', 'Ould Yengé', 'Ghabou'],
    },
    {
        'nom': 'Hodh Ech Chargui',
        'communes': ['Néma', 'Amourj', 'Bassikounou', 'Djiguenni', 'Oualata', 'Timbedra'],
    },
    {
        'nom': 'Hodh El Gharbi',
        'communes': ['Aïoun', 'Kobenni', 'Tamchekett', 'Tintane'],
    },
    {
        'nom': 'Inchiri',
        'communes': ['Akjoujt', 'Bennichab'],
    },
    {
        'nom': 'Tagant',
        'communes': ['Tidjikja', 'Moudjéria', 'Tichitt'],
    },
    {
        'nom': 'Tiris Zemmour',
        'communes': ['Zouérat', 'Bir Moghrein', 'F’dérik'],
    },
    {
        'nom': 'Trarza',
        'communes': ['Rosso', 'Boutilimit', 'Keur Macène', 'Mederdra', 'Ouad Naga', 'R’Kiz'],
    },
]

COMMUNE_AUTRE_LABEL = 'Autre (préciser)'

