# Generated by Django 5.2.13 on 2026-06-17 11:10

import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.comparison
import django.db.models.functions.datetime
import django.db.models.functions.text
import etudiants.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.IntegerField(unique=True)),
                ('num_bac', models.CharField(max_length=50, verbose_name='N° de Bac')),
                ('nni', models.CharField(max_length=10, unique=True, verbose_name='NNI')),
                ('sexe', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], max_length=1, verbose_name='Sexe')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('nom_famille', models.CharField(max_length=100, verbose_name='Nom de famille')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(max_length=100, verbose_name='Lieu de naissance')),
                ('nationalite', models.CharField(max_length=100, verbose_name='Nationalité')),
                ('categorie_bac', models.CharField(choices=[('National', 'National'), ('Etranger', 'Étranger')], max_length=50, verbose_name='Catégorie Bac')),
                ('serie_bac', models.CharField(choices=[('C', 'Mathématiques'), ('D', 'Sciences de la Nature'), ('TMGM', 'Techniques et Méthodes Générales de Mathématiques'), ('TSGM', 'Techniques sciences génie mécanique'), ('LM', 'Lettres Modernes'), ('LO', 'Lettres Originelles'), ('Etrangere', 'Série étrangère')], max_length=50, verbose_name='Série Bac')),
                ('moyenne_bac', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Moyenne Bac')),
                ('ecole_bac', models.CharField(max_length=150, verbose_name="École d'obtention du Bac")),
                ('date_premiere_inscription', models.DateField(verbose_name='Date de 1ère inscription')),
                ('annee_premiere_inscription', models.GeneratedField(db_persist=True, expression=models.Case(models.When(date_premiere_inscription__month__gte=9, then=django.db.models.functions.text.Concat(django.db.models.functions.comparison.Cast(django.db.models.functions.datetime.ExtractYear('date_premiere_inscription'), models.CharField()), models.Value('-'), django.db.models.functions.comparison.Cast(django.db.models.expressions.CombinedExpression(django.db.models.functions.datetime.ExtractYear('date_premiere_inscription'), '+', models.Value(1)), models.CharField()))), default=django.db.models.functions.text.Concat(django.db.models.functions.comparison.Cast(django.db.models.expressions.CombinedExpression(django.db.models.functions.datetime.ExtractYear('date_premiere_inscription'), '-', models.Value(1)), models.CharField()), models.Value('-'), django.db.models.functions.comparison.Cast(django.db.models.functions.datetime.ExtractYear('date_premiere_inscription'), models.CharField()))), output_field=models.CharField(max_length=9, verbose_name='Année de 1ère inscription'))),
                ('voie_acces', models.CharField(choices=[('1', 'Voie 1 Interne'), ('2', 'Voie 1 Externe'), ('3', 'Voie 2 Interne'), ('4', 'Voie 2 Externe')], max_length=20, verbose_name="Voie d'accès")),
                ('diplome_acces', models.CharField(max_length=100, verbose_name="Diplôme d'accès")),
                ('etablissement_diplome', models.CharField(blank=True, max_length=150, null=True, verbose_name='Établissement du diplôme')),
                ('adresse_primaire', models.TextField(verbose_name='Adresse principale')),
                ('adresse_secondaire', models.TextField(blank=True, null=True, verbose_name='Adresse secondaire')),
                ('resident_avec_parents', models.BooleanField(default=True, verbose_name='Réside avec ses parents')),
                ('compte_bankily', models.CharField(blank=True, max_length=50, null=True, verbose_name='Compte Bankily')),
                ('email_pro', models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Concat(django.db.models.functions.comparison.Cast(models.F('matricule'), output_field=models.CharField()), models.Value('@esp.mr')), output_field=models.EmailField(max_length=254))),
                ('email_perso', models.EmailField(max_length=254, verbose_name='Email personnel')),
                ('tel1', models.CharField(max_length=8, verbose_name='Téléphone 1')),
                ('tel2_whatsapp', models.CharField(blank=True, max_length=8, null=True, verbose_name='WhatsApp')),
                ('facebook', models.CharField(blank=True, max_length=150, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('moyenne_bac__gte', 0), ('moyenne_bac__lte', 20)), name='check_moyenne_bac_range')],
            },
        ),
        migrations.CreateModel(
            name='DossierMilitaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compagnie', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('sport_pratique', models.CharField(max_length=100)),
                ('tour_poitrine', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tour_ceinture', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tour_taille', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tour_bassin', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tour_cou', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('longueur_manche', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('longueur_dos', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('longueur_cote', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pointure', models.IntegerField(blank=True, null=True)),
                ('eleve', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier_militaire', to='etudiants.eleve')),
            ],
        ),
        migrations.CreateModel(
            name='DossierAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departement', models.CharField(choices=[('IRT', 'Informatique, Réseaux et Télécommunications'), ('SID', 'Statistique et Ingénierie des Données'), ('GE', 'Génie Électrique'), ('GM', 'Génie Mécanique'), ('GC-HE', 'Génie Civil'), ('MPG', 'Mines, Pétrole et Gaz')], max_length=50)),
                ('niveau_actuel', models.CharField(choices=[('3', '3e Année'), ('4', '4e Année'), ('4-DD', '4e Année Double Diplôme'), ('4-E', '4e Année Échange'), ('5-DD', '5e Année Double Diplôme')], max_length=20)),
                ('semestre_actuel', models.CharField(choices=[('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3'), ('S4', 'S4'), ('S5', 'S5'), ('S6', 'S6'), ('S7', 'S7'), ('S8', 'S8')], max_length=10)),
                ('donnees_semestres', models.JSONField(blank=True, default=dict, null=True)),
                ('diplome', models.CharField(blank=True, max_length=100, null=True)),
                ('etablissement_echange', models.CharField(blank=True, max_length=150, null=True)),
                ('etablissement_double_diplome', models.CharField(blank=True, max_length=150, null=True)),
                ('specialite_mobilite', models.CharField(blank=True, max_length=150, null=True)),
                ('parcours', models.CharField(max_length=100)),
                ('eleve', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier_academique', to='etudiants.eleve')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin', models.FileField(blank=True, null=True, upload_to='documents/cin/', validators=[etudiants.validators.validate_document_file])),
                ('acte_naissance', models.FileField(blank=True, null=True, upload_to='documents/acte_naissance/', validators=[etudiants.validators.validate_document_file])),
                ('diplome_acces', models.FileField(blank=True, null=True, upload_to='documents/diplome_acces/', validators=[etudiants.validators.validate_document_file])),
                ('diplome_bac', models.FileField(blank=True, null=True, upload_to='documents/diplome_bac/', validators=[etudiants.validators.validate_document_file])),
                ('photo_identite_militaire', models.ImageField(blank=True, null=True, upload_to='documents/photos/militaire/', validators=[etudiants.validators.validate_image_resolution])),
                ('photo_identite_civile', models.ImageField(blank=True, null=True, upload_to='documents/photos/civile/', validators=[etudiants.validators.validate_image_resolution])),
                ('photo_militaire_integrale', models.ImageField(blank=True, null=True, upload_to='documents/photos/integrale/', validators=[etudiants.validators.validate_image_resolution])),
                ('eleve', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='etudiants.eleve')),
            ],
        ),
        migrations.CreateModel(
            name='ContactParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom_pere', models.CharField(max_length=100)),
                ('nom_famille_pere', models.CharField(max_length=100)),
                ('fonction_pere', models.CharField(blank=True, max_length=100, null=True)),
                ('tel_pere', models.CharField(blank=True, max_length=8, null=True)),
                ('tel_pere_whatsapp', models.CharField(blank=True, max_length=8, null=True)),
                ('prenom_mere', models.CharField(blank=True, max_length=100, null=True)),
                ('nom_famille_mere', models.CharField(blank=True, max_length=100, null=True)),
                ('fonction_mere', models.CharField(blank=True, max_length=100, null=True)),
                ('tel_mere', models.CharField(blank=True, max_length=8, null=True)),
                ('tel_mere_whatsapp', models.CharField(blank=True, max_length=8, null=True)),
                ('nom_urgence', models.CharField(blank=True, max_length=150, null=True)),
                ('tel_urgence', models.CharField(max_length=8)),
                ('tel_urgence_whatsapp', models.CharField(blank=True, max_length=8, null=True)),
                ('eleve', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contacts_parents', to='etudiants.eleve')),
            ],
        ),
        migrations.CreateModel(
            name='Hebergement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batiment', models.CharField(max_length=100)),
                ('etage', models.CharField(max_length=50)),
                ('aile', models.CharField(max_length=50)),
                ('chambre', models.CharField(max_length=50)),
                ('lit', models.CharField(max_length=50)),
                ('responsable_chambre', models.BooleanField(default=False)),
                ('responsable_aile', models.BooleanField(default=False)),
                ('responsable_etage', models.BooleanField(default=False)),
                ('eleve', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hebergement', to='etudiants.eleve')),
            ],
        ),
        migrations.CreateModel(
            name='DossierSante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe_sanguin', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('assureur', models.CharField(blank=True, max_length=100, null=True)),
                ('num_assure', models.CharField(blank=True, max_length=100, null=True)),
                ('antecedents_medicaux', models.TextField(blank=True, null=True)),
                ('maladies_chroniques', models.TextField(blank=True, null=True)),
                ('medicaments_a_vie', models.TextField(blank=True, null=True)),
                ('poids_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('taille_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('imc', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('poids_kg'), '/', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('taille_cm'), '/', models.Value(100)), '^', models.Value(2))), output_field=models.DecimalField(decimal_places=2, max_digits=5))),
                ('eleve', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier_sante', to='etudiants.eleve')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('taille_cm__gt', 0), ('taille_cm__isnull', True), _connector='OR'), name='check_taille_cm_notzero')],
            },
        ),
    ]
