# Generated by Django 5.2.13 on 2026-09-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossieracademique',
            name='annee_debut_mobilite',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dossieracademique',
            name='annee_fin_mobilite',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dossieracademique',
            name='raison_mobilite',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dossieracademique',
            name='type_mobilite',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='dossiersante',
            name='dossier_medical_pdf',
            field=models.FileField(blank=True, null=True, upload_to='dossiers_sante/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='dossiersante',
            name='photo_medicale',
            field=models.FileField(blank=True, null=True, upload_to='dossiers_sante/photos/%Y/%m/'),
        ),
    ]
