# Generated by Django 5.2.13 on 2026-09-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0002_phase9_operations_scolarite'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='eleve',
            name='row_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='eleve',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
