# Generated by Django 5.2.13 on 2026-09-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0003_phase12_13_version_and_student'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dossieracademique',
            index=models.Index(fields=['departement'], name='acad_departement_idx'),
        ),
        migrations.AddIndex(
            model_name='dossieracademique',
            index=models.Index(fields=['niveau_actuel'], name='acad_niveau_actuel_idx'),
        ),
        migrations.AddIndex(
            model_name='dossieracademique',
            index=models.Index(fields=['departement', 'niveau_actuel'], name='acad_dept_niveau_idx'),
        ),
        migrations.AddIndex(
            model_name='dossiermilitaire',
            index=models.Index(fields=['compagnie'], name='mil_compagnie_idx'),
        ),
        migrations.AddIndex(
            model_name='dossiermilitaire',
            index=models.Index(fields=['section'], name='mil_section_idx'),
        ),
        migrations.AddIndex(
            model_name='dossiermilitaire',
            index=models.Index(fields=['compagnie', 'section'], name='mil_compagnie_section_idx'),
        ),
        migrations.AddIndex(
            model_name='eleve',
            index=models.Index(fields=['nom_famille', 'prenom'], name='eleve_nom_prenom_idx'),
        ),
        migrations.AddIndex(
            model_name='eleve',
            index=models.Index(fields=['date_naissance'], name='eleve_date_naissance_idx'),
        ),
        migrations.AddIndex(
            model_name='eleve',
            index=models.Index(fields=['-updated_at'], name='eleve_updated_at_idx'),
        ),
        migrations.AddIndex(
            model_name='eleve',
            index=models.Index(fields=['created_at'], name='eleve_created_at_idx'),
        ),
    ]
