# Generated by Django 5.2.13 on 2026-09-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0008_eleve_profil_incomplet_blankable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossieracademique',
            name='niveau_actuel',
            field=models.CharField(choices=[('3', '3e année'), ('4', '4e année'), ('4-DD', '4e DD'), ('4-E', '5e E'), ('5-DD', '5e DD')], max_length=20),
        ),
    ]
